CREATE DATABASE Anime
GO
USE Anime
GO



CREATE TABLE Directors(
DID INT PRIMARY KEY,
DirectorName VARCHAR(50))

CREATE TABLE VoiceActors(
VAID INT PRIMARY KEY,
ActorName VARCHAR(50),
Gender VARCHAR(6))

CREATE TABLE Studios(
STID INT PRIMARY KEY,
StudioName VARCHAR(50),
Founder VARCHAR(50),
YearlyGrossing INT)

CREATE TABLE Composers(
CID INT PRIMARY KEY,
ComposeName VARCHAR(50))

CREATE TABLE Characters(
CHID INT PRIMARY KEY,
CharacterName VARCHAR(50),
Gender VARCHAR(6))

CREATE TABLE Manga(
MID INT PRIMARY KEY,
Title VARCHAR(50),
Author VARCHAR(50)
)

CREATE TABLE Anime(
AID INT PRIMARY KEY,
Title VARCHAR(50),
Movie BIT,
EpisodeCount INT,
MID INT FOREIGN KEY REFERENCES Manga(MID),
Rating INT CHECK (Rating >=0 AND Rating <=10),
STID INT FOREIGN KEY REFERENCES Studios(STID)
)

CREATE TABLE DirectsAnime(
DID INT FOREIGN KEY REFERENCES Directors(DID),
AID INT FOREIGN KEY REFERENCES Anime(AID),
CONSTRAINT pk_Directs PRIMARY KEY(DID, AID))

CREATE TABLE ActingInAnime(
AID INT FOREIGN KEY REFERENCES Anime(AID),
VAID INT FOREIGN KEY REFERENCES VoiceActors(VAID),
CHID INT FOREIGN KEY REFERENCES Characters(CHID),
CONSTRAINT pk_Acting PRIMARY KEY(AID, VAID))

CREATE TABLE WorksAt(
DID INT FOREIGN KEY REFERENCES Directors(DID),
STID INT FOREIGN KEY REFERENCES Studios(STID),
CONSTRAINT pk_Working PRIMARY KEY(DID, STID))

DROP TABLE WorksAt

CREATE TABLE OST(
CHID INT FOREIGN KEY REFERENCES Characters(CHID),
CONSTRAINT pk_OST PRIMARY KEY(CHID),
Lengthy TIME,
Genre VARCHAR(50),
Album VARCHAR(50),
CID INT FOREIGN KEY REFERENCES Composers(CID))
